---
- name: Backup IOS-XE Devices
  hosts: ios-xe

  tasks:
    - name: Backup IOS-XE Devices
      cisco.ios.ios_config:
       backup: true
       backup_options:
         filename: "{{ inventory_hostname }}-backup.txt"
         dir_path: ./BACKUPS

- name: Backup Nexus Devices
  hosts: nexus

  tasks:
    - name: Backup Nexus Devices
      cisco.nxos.nxos_config:
       backup: true
       backup_options:
         filename: "{{ inventory_hostname }}-backup.txt"
         dir_path: ./BACKUPS

- name: Backup IOS-XR Devices
  hosts: iosxr

  tasks:
    - name: Backup IOS-XR Devices
      cisco.iosxr.iosxr_config:
       backup: true
       backup_options:
         filename: "{{ inventory_hostname }}-backup.txt"
         dir_path: ./BACKUPS