---
- name: BIG-IP
  hosts: big-ip-f5
  connection: local
  gather_facts: false

  tasks:
    - name: Create pool
      bigip_pool:
        state: present
        name: my-pool
        partition: Common
        lb_method: least-connections-member
        slow_ramp_time: 120
        provider:
          server: lb.mydomain.com
          user: admin
          password: admin
          validate_certs: false
      delegate_to: localhost